spring:
  application:
    name: beverage-erp
  
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_erp
    username: postgres
    password: estudiantes473
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # Obligatorio usar validate porque usaremos Flyway 
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  flyway:
    enabled: true
    baseline-on-migrate: true
