spring:
  application:
    name: beverage-erp
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_erp
    username: postgres
    password: estudiantes473
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate 
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  flyway:
    enabled: true
    baseline-on-migrate: true
  jackson:
    serialization:
      write-dates-as-timestamps: false # Para que salgan como "2026-01-18T..."
    default-property-inclusion: non_null # No enviamos campos nulos para ahorrar ancho de banda
springdoc:
  show-login-endpoint: true
  default-produces-media-type: application/json

# --- PROPIEDADES PERSONALIZADAS DEL SISTEMA (Fuera de 'spring') ---
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 d√≠a